- hosts: localhost
  vars:
    key_personal_src: "keys/id_ed25519"
    key_personal_dst: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    key_setup_src: "keys/id_ed25519_ansible"
    key_setup_dst: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_ansible"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
  pre_tasks:
    - name: Update and upgrade packages
      become: true
      community.general.xbps:
        update_cache: true
        upgrade: true
      tags:
        - setup
        - core
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/void-packages.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/dwm.yml
    - include_tasks: tasks/sddm.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/zsh.yml
    # - include_tasks: tasks/awesome.yml
    - include_tasks: tasks/terminal.yml
    - include_tasks: tasks/dev.yml
    - include_tasks: tasks/cleanup.yml
