- name: Install AwesomeWM dependencies
  become: true
  community.general.xbps:
    name: 
    - pkg-config
    - dbus-devel
    - dbus-x11
    - pango
    - pango-devel
    - gdk-pixbuf-devel
    - libxdg-basedir-devel
    - libXfixes-devel
    - libxkbcommon-devel
    - libxkbcommon-x11
    - LuaJIT
    - LuaJIT-devel
    - lua53
    - lua53-devel
    - lua53-lgi
    - luarocks-lua53
    - startup-notification-devel
    - libxcb-devel
    - xcb-util-devel
    - xcb-util-cursor-devel
    - xcb-util-image-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - xcb-util-xrm-devel
    - xcb-util-errors-devel
    - ruby-asciidoctor
    - cmake
    - docbook-xsl
    - git
    - ImageMagick
    state: present

- name: Install AwesomeWM optional dependencies
  become: true
  community.general.xbps:
    name: 
    - xmlto
    - dex
    - librsvg
    - rlwrap
    state: present

- name: AwesomeWM checkout
  git:
    repo: https://github.com/awesomeWM/awesome.git
    dest: /tmp/awesome
    force: true

- name: Remove build directory if it exists
  ansible.builtin.file:
    path: /tmp/awesome/build
    state: absent

- name: Make AwesomeWM
  shell: 'CMAKE_ARGS="-DLUA_EXECUTABLE=/usr/bin/lua5.3 -DLUA_LIBRARY=/usr/lib/liblua5.3.so -DLUA_INCLUDE_DIR=/usr/include/lua5.3" make'
  args:
    chdir: /tmp/awesome

- name: Install AwesomeWM
  become: true
  shell: "make install"
  args:
    chdir: /tmp/awesome

- name: Checkout Awesome Bling
  git:
    repo: 'https://github.com/BlingCorp/bling.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/awesome/bling"
