- name: Install AwesomeWM dependencies
  become: true
  community.general.xbps:
    name: 
    - pkg-config
    - dbus-devel
    - dbus-x11
    - pango
    - pango-devel
    - gdk-pixbuf-devel
    - libxdg-basedir-devel
    - libXfixes-devel
    - libxkbcommon-devel
    - libxkbcommon-x11
    - LuaJIT
    - LuaJIT-devel
    - lua51-lgi
    - luarocks-lua51
    - startup-notification-devel
    - libxcb-devel
    - xcb-util-devel
    - xcb-util-cursor-devel
    - xcb-util-image-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - xcb-util-xrm-devel
    - xcb-util-errors
    - ruby-asciidoctor
    - cmake
    - docbook-xsl
    - git
    - ImageMagick
    state: present

- name: Install AwesomeWM optional dependencies
  become: true
  community.general.xbps:
    name: 
    - xmlto
    - dex
    - librsvg
    - rlwrap
    state: present

- name: AwesomeWM checkout
  git:
    repo: https://github.com/awesomeWM/awesome.git
    dest: "/tmp/awesome"

- name: Change used lua binary (LuaJIT Only)
  shell: sed -e "s|COMMAND lua\b|COMMAND luajit|" -i awesomeConfig.cmake -i tests/examples/CMakeLists.txt
  args:
    chdir: "/tmp/awesome"

- name: Change used lua binary (LuaJIT Only)
  shell: sed -e "s|LUA_COV_RUNNER lua\b|LUA_COV_RUNNER luajit|" -i tests/examples/CMakeLists.txt
  args:
    chdir: "/tmp/awesome"

- name: Make AwesomeWM
  shell: 'CMAKE_ARGS="-DLUA_EXECUTABLE=/usr/bin/luajit -DLUA_LIBRARY=/usr/lib/liblua.so.5.3 -DLUA_INCLUDE_DIR=/usr/include/lua5.3" make'
  args:
    chdir: "/tmp/awesome"

- name: Install AwesomeWM
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/awesome"
