- name: Install AwesomeWM dependencies
  become: true
  community.general.xbps:
    name: 
    - cairo
    - dbus
    - gdk-pixbuf
    - libxdg-basedir
    - libXfixes
    - libxkbcommon-x11
    - LuaJIT
    - LuaJIT-devel
    - pango
    - startup-notification
    - xcb-util-cursor 
    - xcb-util-keysyms
    - xcb-util-wm
    - xcb-util-xrm
    - asciidoc
    - cmake
    - docbook-xsl
    - git
    - ImageMagick
    - xmlto
    - dex
    - librsvg
    - rlwrap
    - xcb-util-errors
    state: present

- name: AwesomeWM checkout
  git:
    repo: https://github.com/awesomeWM/awesome.git
    dest: "/tmp/awesome"

- name: Make AwesomeWM
  shell: "make"
  args:
    chdir: "/tmp/awesome"

- name: Install AwesomeWM
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/awesome"
