- name: Install AwesomeWM dependencies
  become: true
  community.general.xbps:
    name: 
    - cairo
    - dbus
    - gdk-pixbuf-devel
    - libxdg-basedir-devel
    - libXfixes
    - libxkbcommon
    - libxkbcommon-devel
    - libxkbcommon-x11
    - LuaJIT
    - LuaJIT-devel
    - lua
    - lua-devel
    - lgi
    - pango
    - startup-notification-devel
    - xcb-util-devel
    - xcb-util-cursor-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - xcb-util-xrm-devel
    - asciidoc
    - cmake
    - docbook-xsl
    - git
    - ImageMagick
    - xmlto
    - dex
    - librsvg
    - rlwrap
    - xcb-util-errors
    state: present

- name: AwesomeWM checkout
  git:
    repo: https://github.com/awesomeWM/awesome.git
    dest: "/tmp/awesome"

- name: Make AwesomeWM
  shell: "make"
  args:
    chdir: "/tmp/awesome"

- name: Install AwesomeWM
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/awesome"
