- name: Install system packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - mkcert
      - python
      - python-pipx
    state: present
  tags:
    - setup
    - core

- name: CLI tools
  become: true
  community.general.pacman:
    name:
      - 7zip
      - bat
      - bc
      - bind
      - btop
      - curl
      - eza
      - fd
      - fwupd
      - fzf
      - gum
      - htop
      - imagemagick
      - lynx
      - nano
      - newsboat
      - pandoc-cli
      - pulsemixer
      - redshift
      - ripgrep
      - texlive
      - texlive-binextra
      - tmux
      - traceroute
      - tree
      - unzip
      - wget
      - whois
      - yay
      - yazi
      - zellij
      - zoxide
    state: present
  tags:
    - setup
    - core

- name: Install calcure
  shell: pipx install --include-deps calcure

- name: Remove tldr
  become: true
  community.general.pacman:
    name:
      - tldr
    state: absent
  tags:
    - setup
    - core

- name: Install tealdeer
  become: true
  community.general.pacman:
    name:
      - tealdeer
    state: present
  tags:
    - setup
    - core

- name: Desktop environment
  become: true
  community.general.pacman:
    name:
      - adapta-gtk-theme
      - alacritty
      - arc-icon-theme
      - blender
      - calibre
      - chromium
      - dunst
      - feh
      - firefox
      - flameshot
      - gimp
      - greetd-tuigreet
      - inkscape
      - lxappearance-gtk3
      - lxsession
      - maim
      - network-manager-applet
      - numlockx
      - papirus-icon-theme
      - picom
      - pngquant
      - poppler
      - qtile
      - rofi
      - scrot
      - starship
      - steam
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - torbrowser-launcher
      - unclutter
      - wezterm
      - xautolock
      - xclip
      - xdg-desktop-portal
      - xf86-input-wacom
      - xsel
      - xterm
      - zathura
      - zathura-pdf-poppler
    state: present
    extra_args: --noconfirm

- name: Clone i3lock-color
  git:
    repo: https://github.com/Raymo111/i3lock-color.git
    dest: /tmp/i3lock-color
    force: true

- name: Install i3lock-color
  shell: bash install-i3lock-color.sh
  args:
    chdir: /tmp/i3lock-color

# - name: Create X11 conf dir if not exists
#   become: true
#   ansible.builtin.file:
#     path: /etc/X11/xorg.conf.d
#     state: directory

# - name: Create X11 conf for evdi to support displaylink screens
#   become: true
#   copy:
#     dest: /etc/X11/xorg.conf.d/20-evdi.conf
#     content: |
#       Section "OutputClass"
#       Identifier "DisplayLink"
#       MatchDriver "evdi"
#       Driver "modesetting"
#       Option "AccelMethod" "none"
#       EndSection

# - name: Set keyboard layout
# become: true
# copy:
# dest: /etc/X11/xorg.conf.d/00-keyboard.conf
# content: |
# Section "InputClass"
# Identifier "system-keyboard"
# MatchIsKeyboard "on"
# Option "XkbLayout" "ch"
# Option "XkbModel" "pc104"
# Option "XkbVariant" "de"
# EndSection

- name: Create user dirs
  shell: xdg-user-dirs-update --force

# - name: Virtualization
#   become: true
#   community.general.pacman:
#     name:
#       - qemu-full
#       - libvirt
#       - cockpit
#     state: present
#
# - name: Enable libvirt service
#   become: true
#   ansible.builtin.systemd_service:
#     name: libvirt
#     enabled: true
#     force: true
#
# - name: Add user steven to group libvirt
#   ansible.builtin.user:
#     name: steven
#     shell: /bin/zsh
#     groups: libvirt
#     append: yes

- name: Multimedia
  become: true
  community.general.pacman:
    name:
      - mpv
      - ffmpeg
    state: present

- name: Fonts
  become: true
  community.general.pacman:
    name:
      - otf-firamono-nerd
      - otf-droid-nerd
      - ttf-3270-nerd
      - ttf-cascadia-code-nerd
      - ttf-fantasque-nerd
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - ttf-noto-nerd
      - ttf-roboto-mono-nerd
      - ttf-roboto
      - ttf-font-awesome
      - ttf-joypixels
    state: present

- name: Install Tmux Plugin Manager TPM
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: Install bluetooth modules and tools
  become: true
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present
    extra_args: --noconfirm

# - name: Nvidia PRIME dependencies
#   become: true
#   community.general.pacman:
#     name:
#       - xf86-video-nouveau
#       - vulkan-mesa-layers
#       - lib32-vulkan-mesa-layers
#     state: present

# - name: Remove nvidia-utils.conf, as it blacklists nouveau
#   shell: /usr/lib/modprobe.d/nvidia-utils.conf
#   ignore_errors: true

- name: Enable bluetooth service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    force: true
# Removed, DisplayLink won't start anymored, can't boot into system this way
# - name: Enable nvidia kernel model setting for sway support
#   become: true
#   copy:
#     dest: "/etc/modprobe.d/nvidia-drm.conf"
#     content: |
#       options nvidia_drm modeset=1 fbdev=1
