- name: Install system packages
  become: true
  community.general.pacman:
    name:
    - base-devel
    - cmake
    - acl
    - python
    - python-pipx
    state: present
  tags:
  - setup
  - core

- name: CLI tools
  become: true
  community.general.pacman:
    name: 
    - bc
    - tree
    - tldr
    - imagemagick
    - pulsemixer
    - fzf
    - fd
    - tmux
    - exa
    - nano
    - bat
    - htop
    - ripgrep
    - unzip
    - wget
    - curl
    - fwupd
    - yay
    state: present
  tags:
  - setup
  - core

- name: Install calcure
  shell: pipx install --include-deps calcure

- name: Desktop environment
  become: true
  community.general.pacman:
    name: 
    - xorg
    - ibus
    - xautolock
    # - i3lock-color
    - maim
    - unclutter
    - dunst
    - feh
    - xclip
    - xsel
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - gsettings-desktop-schemas
    - direnv
    - lxappearance-gtk3
    - lxsession
    - picom
    - starship
    - rofi
    - xdg-user-dirs
    - xdg-desktop-portal-gtk
    - xf86-input-evdev
    - xf86-input-libinput
    - xf86-input-synaptics
    - xf86-input-vmmouse
    - xf86-input-wacom
    - xf86-video-amdgpu
    - xf86-video-intel
    - xf86-video-nouveau
    - xf86-video-openchrome
    - xf86-video-qxl
    - xf86-video-vmware
    - zathura
    - zathura-pdf-poppler
    - firefox
    - chromium
    - alacritty
    - xterm
    - qtile
    - awesome
    - polybar
    - arc-gtk-theme-eos
    - adapta-gtk-theme
    - arc-icon-theme
    - papirus-icon-theme
    - greetd-tuigreet
    - vicious # awesome
    - dex     # awesome
    - rlwrap  # awesome 
    - imlib2  # awesome
    state: present

# - name: Create X11 conf dir if not exists
  # become: true
  # ansible.builtin.file:
    # path: /etc/X11/xorg.conf.d
    # state: directory

# - name: Set keyboard layout
  # become: true
  # copy:
    # dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    # content: |
# Section "InputClass"
# Identifier "system-keyboard"
# MatchIsKeyboard "on"
# Option "XkbLayout" "ch"
# Option "XkbModel" "pc104"
# Option "XkbVariant" "de"
# EndSection

- name: Create user dirs
  shell: xdg-user-dirs-update --force

- name: Checkout Awesome Bling
  git:
    repo: 'https://github.com/BlingCorp/bling.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/awesome/bling"

- name: Virtualization
  become: true
  community.general.pacman:
    name:
    - qemu
    state: present

- name: Multimedia
  become: true
  community.general.pacman:
    name: 
    - mpv
    - ffmpeg
    state: present

- name: Fonts
  become: true
  community.general.pacman:
    name: 
    - ttf-fantasque-nerd
    - ttf-hack-nerd
    - ttf-iosevkaterm-nerd
    - ttf-noto-nerd
    - ttf-roboto-mono-nerd
    - ttf-font-awesome
    - awesome-terminal-fonts
    state: present
 
- name: Checkout Qogir Theme
  git:
    repo: https://github.com/vinceliuice/Qogir-theme
    dest: /tmp/qogir

- name: Install Qogir Theme
  shell: bash install.sh
  args:
    chdir: /tmp/qogir

