- name: Install system packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - python
      - python-pipx
      - mkcert
    state: present
  tags:
    - setup
    - core

- name: CLI tools
  become: true
  community.general.pacman:
    name:
      - bc
      - bind
      - whois
      - traceroute
      - tree
      - tealdeer
      - imagemagick
      - pulsemixer
      - fzf
      - fd
      - tmux
      - nano
      - bat
      - htop
      - ripgrep
      - unzip
      - wget
      - curl
      - fwupd
      - yay
      - p7zip
      - pandoc-cli
      - texlive
      - texlive-binextra
    state: present
  tags:
    - setup
    - core

- name: Install calcure
  shell: pipx install --include-deps calcure

- name: Tools
  become: true
  community.general.pacman:
    name:
      - xf86-input-wacom
      - zathura
      - zathura-pdf-poppler
      - firefox
      - newsboat
      - torbrowser-launcher
      - chromium
      - gimp
      - blender
      - inkscape
      - qemu-full
      - mpv
      - ffmpeg
    state: present
    extra_args: --noconfirm

- name: Clone i3lock-color
  git:
    repo: https://github.com/Raymo111/i3lock-color.git
    dest: /tmp/i3lock-color
    force: true

- name: Install i3lock-color
  shell: bash install-i3lock-color.sh
  args:
    chdir: /tmp/i3lock-color

- name: Create user dirs
  shell: xdg-user-dirs-update --force
# - name: Create X11 conf dir if not exists
#   become: true
#   ansible.builtin.file:
#     path: /etc/X11/xorg.conf.d
#     state: directory

# - name: Create X11 conf for evdi to support displaylink screens
#   become: true
#   copy:
#     dest: /etc/X11/xorg.conf.d/20-evdi.conf
#     content: |
# Section "OutputClass"
# Identifier "DisplayLink"
# MatchDriver "evdi"
# Driver "modesetting"
# Option "AccelMethod" "none"
# EndSection

# - name: Set keyboard layout
# become: true
# copy:
# dest: /etc/X11/xorg.conf.d/00-keyboard.conf
# content: |
# Section "InputClass"
# Identifier "system-keyboard"
# MatchIsKeyboard "on"
# Option "XkbLayout" "ch"
# Option "XkbModel" "pc104"
# Option "XkbVariant" "de"
# EndSection
