- name: Install system packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - python
      - python-pipx
      - mkcert
    state: present
  tags:
    - setup
    - core

- name: CLI tools
  become: true
  community.general.pacman:
    name:
      - bc
      - bind
      - btop
      - whois
      - traceroute
      - tree
      - imagemagick
      - pulsemixer
      - fzf
      - fd
      - tmux
      - nano
      - bat
      - htop
      - ripgrep
      - unzip
      - wget
      - curl
      - fwupd
      - yay
      - pandoc-cli
      - texlive
      - texlive-binextra
    state: present
  tags:
    - setup
    - core

- name: Install calcure
  shell: pipx install --include-deps calcure

- name: Remove tldr
  become: true
  community.general.pacman:
    name:
      - tldr
    state: absent
  tags:
    - setup
    - core

- name: Install tealdeer
  become: true
  community.general.pacman:
    name:
      - tealdeer
    state: present
  tags:
    - setup
    - core

- name: Desktop environment
  become: true
  community.general.pacman:
    name:
      - xautolock
      - nvidia-utils
      - maim
      - pngquant
      - unclutter
      - dunst
      - feh
      - xclip
      - xsel
      - wezterm
      - scrot
      - numlockx
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - lxappearance-gtk3
      - lxsession
      - picom
      - calibre
      - poppler
      - starship
      - rofi
      - xf86-input-wacom
      - flameshot
      - zathura
      - zathura-pdf-poppler
      - firefox
      - newsboat
      - torbrowser-launcher
      - chromium
      - alacritty
      - chromium
      - gimp
      - blender
      - inkscape
      - xterm
      - qtile
      - steam
      - awesome
      - polybar
      - adapta-gtk-theme
      - arc-icon-theme
      - papirus-icon-theme
      - greetd-tuigreet
      - vicious # awesome
      - dex # awesome
      - rlwrap # awesome
      - imlib2 # awesome
      - xdg-desktop-portal
      - xf86-video-nouveau
    state: present
    extra_args: --noconfirm

- name: Clone i3lock-color
  git:
    repo: https://github.com/Raymo111/i3lock-color.git
    dest: /tmp/i3lock-color
    force: true

- name: Install i3lock-color
  shell: bash install-i3lock-color.sh
  args:
    chdir: /tmp/i3lock-color

- name: Create X11 conf dir if not exists
  become: true
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Create X11 conf for evdi to support displaylink screens
  become: true
  copy:
    dest: /etc/X11/xorg.conf.d/20-evdi.conf
    content: |
      Section "OutputClass"
      Identifier "DisplayLink"
      MatchDriver "evdi"
      Driver "modesetting"
      Option "AccelMethod" "none"
      EndSection

# - name: Set keyboard layout
# become: true
# copy:
# dest: /etc/X11/xorg.conf.d/00-keyboard.conf
# content: |
# Section "InputClass"
# Identifier "system-keyboard"
# MatchIsKeyboard "on"
# Option "XkbLayout" "ch"
# Option "XkbModel" "pc104"
# Option "XkbVariant" "de"
# EndSection

- name: Create user dirs
  shell: xdg-user-dirs-update --force

- name: Virtualization
  become: true
  community.general.pacman:
    name:
      - qemu-full
    state: present

- name: Multimedia
  become: true
  community.general.pacman:
    name:
      - mpv
      - ffmpeg
    state: present

- name: Fonts
  become: true
  community.general.pacman:
    name:
      - otf-firamono-nerd
      - otf-droid-nerd
      - ttf-3270-nerd
      - ttf-cascadia-code-nerd
      - ttf-fantasque-nerd
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - ttf-noto-nerd
      - ttf-roboto-mono-nerd
      - ttf-roboto
      - ttf-font-awesome
      - ttf-joypixels
    state: present

- name: Install Tmux Plugin Manager TPM
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: Install bluetooth modules and tools
  become: true
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present
    extra_args: --noconfirm

- name: Enable bluetooth service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    force: true
# Removed, DisplayLink won't start anymored, can't boot into system this way
# - name: Enable nvidia kernel model setting for sway support
#   become: true
#   copy:
#     dest: "/etc/modprobe.d/nvidia-drm.conf"
#     content: |
#       options nvidia_drm modeset=1 fbdev=1
