- name: Install docker
  become: true
  community.general.pacman:
    name:
      - docker
    state: present

- name: Enable docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    force: true

- name: (AUR) Install dependencies to run docker rootless
  kewlfft.aur.aur:
    use: yay
    state: present
    name:
      - docker-rootless-extras

- name: Create /etc/subuid
  become: true
  copy:
    dest: /etc/subuid
    content: |
      steven:231072:65536

- name: Create /etc/subgid
  become: true
  copy:
    dest: /etc/subgid
    content: |
      steven:231072:65536

- name: Enable socket-activation for the user service
  become: true
  ansible.builtin.systemd_service:
    scope: user
    name: docker.socket
    enabled: true
    force: true
