- name: Install stow
  become: true
  community.general.xbps:
    name: 
    - stow
    state: present
  tags:
    - setup
    - dotfiles

- name: Add key
  shell: "ssh-add -K ~/.ssh/id_ed25519"

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:Wolfi/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_newhostkey: yes
    version: master
  tags:
    - setup
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow.sh
  tags:
    - setup
    - dotfiles
