- name: Install dwm dependencies
  become: true
  community.general.pacman:
    name: 
    - dmenu
    - libx11
    - libxft
    - libxinerama
    state: present

- name: dwm checkout
  git:
    repo: git@github.com:wolfi/dwm.git
    dest: "{{ lookup('env', 'HOME') }}/personal/dwm"
    update: yes
    accept_newhostkey: yes
    key_file: "{{ key_setup_dst }}" 

- name: Run make and install as root
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/dwm"
    targets:
    - clean
    - install
  become: true

- name: Create dwm xsession file
  become: true
  copy:
    dest: "/usr/share/xsessions/dwm.desktop"
    content: |
      [Desktop Entry]
      Name=dwm
      Comment=Highly configurable framework window manager
      TryExec=dwm
      Exec=dwm
      Type=Application

- name: dwmblocks checkout
  git:
    repo: https://github.com/torrinfail/dwmblocks
    dest: "{{ lookup('env', 'HOME') }}/personal/dwmblocks"

- name: Run make and install as root
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/dwmblocks"
    targets:
    - clean
    - install
  become: true
