- name: Clone pkms data
  ansible.builtin.git:
    repo: "git@github.com:wolfi/pkms-logseq.git"
    dest: "{{ lookup('env', 'HOME') }}/personal/pkms-logseq"
    update: yes
    accept_newhostkey: yes
    version: main
    key_file: "{{ key_setup_dst }}" 

- name: (AUR) Install Logseq
  kewlfft.aur.aur:
    use: yay
    state: present
    name:
      - logseq-desktop-bin
