- name: Install sddm and dependencies
  become: true
  community.general.pacman:
    name:
    - sddm
    - qt5-quickcontrols2
    - qt5-svg
    - qt5-graphicaleffects
    state: present

- name: Check if sddm theme is already present
  become: true
  stat: 
    path: /usr/share/sddm/themes/rose-pine-theme
  register: sddm_theme_dir

- name: Copy theme
  when: not sddm_theme_dir.stat.exists
  become: true
  copy:
    src: "sddm/rose-pine-theme"
    dest: "/usr/share/sddm/themes/"

- name: Create sddm config dir if not exists
  become: true
  ansible.builtin.file:
    path: /etc/sddm.conf.d
    state: directory

- name: Create dwm xsession file
  become: true
  copy:
    dest: /etc/sddm.conf.d/theme.conf
    content: |
      [Theme]
      Current=rose-pine-theme

- name: Enable sddm service
  become: true
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true
    force: true
