- name: Create .ssh directory
  file:
    dest: "{{ key_personal_dst | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - setup
    - ssh

- name: Install personal private key
  copy:
    src: "{{ key_personal_src }}"
    dest: "{{ key_personal_dst }}"
    mode: 0600
  tags:
    - dotfiles
    - setup
    - ssh

- name: Install personal public key
  copy:
    src: "{{ key_personal_src }}.pub"
    dest: "{{ key_personal_src }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - setup
    - ssh

- name: Install setup private key
  copy:
    src: "{{ key_setup_src }}"
    dest: "{{ key_setup_src }}"
    mode: 0600
  tags:
    - setup

- name: Install setup public key
  copy:
    src: "{{ key_setup_src }}.pub"
    dest: "{{ key_setup_src }}.pub"
    mode: 0644
  tags:
    - setup

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
