- name: Create .ssh directory
  file:
    dest: "{{ key_dst | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - setup
    - ssh

- name: Install ssh key
  copy:
    src: "{{ key_src }}"
    dest: "{{ key_dst }}"
    mode: 0600
  tags:
    - dotfiles
    - setup
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ key_src }}.pub"
    dest: "{{ key_dst }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - setup
    - ssh

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ key_dst }}.pub"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
