- name: Install sway and basic wayland compatible tools
  become: true
  community.general.pacman:
    name:
      - acpi
      - autotiling
      - azote
      - brightnessctl
      - cliphist
      - egl-wayland
      - file-roller
      - fuzzel
      - greetd
      - greetd-regreet
      - grim
      - htop
      - btop
      - jq
      - mako
      - network-manager-applet
      - nwg-drawer
      - nwg-look
      - pamixer
      - polkit-gnome
      - slurp
      - swappy
      - sway
      - sway-contrib
      - swaylock
      - swayidle
      - swaybg
      - sysstat
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - foot
      - foot-terminfo
      - wezterm
      - mako
      - dmenu
      - i3status
      - polkit
      - vulkan-nouveau
      - vulkan-validation-layers
      - waybar
      - wayland-protocols
      - wl-clipboard
      - wmenu
      - yay
      - xed
      - xorg-xwayland
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
    state: present
  tags:
    - setup
    - wayland

- name: Copy wayland start env script
  become: true
  copy:
    src: "wayland/env.sh"
    dest: "/usr/local/bin/env.sh"
    mode: "777"

- name: Copy sway start script
  become: true
  copy:
    src: "wayland/sway-start.sh"
    dest: "/usr/local/bin/sway-start.sh"
    mode: "777"

- name: Copy regreet.toml
  become: true
  copy:
    src: "greetd/regreet.toml"
    dest: "/etc/greetd/regreet.toml"

- name: Create sway xsession file
  become: true
  copy:
    dest: "/usr/share/wayland-sessions/sway-script.desktop"
    content: |
      [Desktop Entry]
      Name=Sway Script
      Comment=An i3-compatible Wayland compositor
      Exec=env XDG_SESSION_TYPE=wayland XDG_SESSION_DESKTOP=sway XDG_CURRENT_DESKTOP=sway MOZ_ENABLE_WAYLAND=1 OZONE_PLATFORM=wayland GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland QT_ENABLE_HIGHDPI_SCALING=1 QT_AUTO_SCREEN_SCALE_FACTOR=1 QT_WAYLAND_RECONNECT=1 SDL_VIDEODRIVER=wayland WLR_RENDERER=gles2 _JAVA_AWT_WM_NONREPARENTING=1 KWIN_DRM_NO_AMS=1 sway --unsupported-gpu
      Type=Application

- name: Create sway xsession file
  become: true
  copy:
    dest: "/usr/share/wayland-sessions/sway.desktop"
    content: |
      [Desktop Entry]
      Name=Sway
      Comment=An i3-compatible Wayland compositor
      Exec=sway --unsupported-gpu
      Type=Application

- name: Install GTK themes
  become: true
  community.general.pacman:
    name:
      - lxappearance-gtk3
      - arc-gtk-theme
      - adapta-gtk-theme
      - qogir-icon-theme
      - arc-icon-theme
      - papirus-icon-theme
      - gtk-engine-murrine
      - gtk-layer-shell
    state: present
  tags:
    - setup
    - gtk

- name: Fonts
  become: true
  community.general.pacman:
    name:
      - awesome-terminal-fonts
      - otf-firamono-nerd
      - otf-droid-nerd
      - ttf-3270-nerd
      - ttf-cascadia-code-nerd
      - ttf-fantasque-nerd
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols-mono
      - ttf-ubuntu-font-family
      - ttf-noto-nerd
      - ttf-roboto-mono-nerd
      - ttf-roboto
      - ttf-font-awesome
      - ttf-joypixels
    state: present
