- name: Install sway and basic wayland compatible tools
  become: true
  community.general.pacman:
    name:
      - sway
      - swaylock
      - swayidle
      - swaybg
      - foot
      - foot-terminfo
      - mako
      - dmenu
      - i3status
      - polkit
      - waybar
      - wmenu
      - xorg-xwayland
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
    state: present
  tags:
    - setup
    - wayland
