- name: Install ST dependencies
  become: true
  community.general.pacman:
    name: 
    - fontconfig
    - libx11
    - libxft
    - harfbuzz
    state: present

- name: ST checkout
  git:
    repo: https://github.com/Wolfi/lukesmithxyz-st
    dest: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"

- name: Run make and install as root
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"
    targets:
    - clean
    - install
  become: true
