- name: Install ST dependencies
  become: true
  community.general.xbps:
    name: 
    - fontconfig-devel
    - libX11-devel
    - libXft-devel
    state: present

- name: ST checkout
  git:
    repo: https://github.com/LukeSmithxyz/st.git
    dest: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"

- name: Run make and install as root
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"
    targets:
    - clean
    - install
  become: true
