- name: Install ST dependencies
  become: true
  community.general.pacman:
    name:
      - tmux
    state: present

- name: Install Tmux Plugin Manager TPM
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
