- name: Install ST dependencies
  become: true
  community.general.pacman:
    name:
      - fontconfig
      - libx11
      - libxft
      - harfbuzz
    state: present

- name: ST checkout
  git:
    repo: git@github.com:wolfi/lukesmithxyz-st.git
    dest: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"
    update: yes
    accept_newhostkey: yes
    key_file: "{{ key_setup_dst }}"

- name: Run make and install as root
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/personal/lukesmith-st"
    targets:
      - clean
      - install
  become: true
