- name: Zsh
  become: true
  community.general.xbps:
    name: 
    - zsh

- name: Antidote checkout
  git:
    repo: https://github.com/mattmc3/antidote.git
    dest: $HOME/.antidote
    force: true
    depth: 1

- name: Run antidote
  shell: $HOME/.antidote/antidote bundle <$HOME/.dotfiles/zsh/.zsh_plugins.txt >~/.zsh_plugins.sh

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
